In [1]:
import pandas as pd
import gdown

In [2]:
gdown.download(id='12b-hMXg0V37w4R9bES88YcH7ousM9y9_')

Downloading...
From: https://drive.google.com/uc?id=12b-hMXg0V37w4R9bES88YcH7ousM9y9_
To: /content/tweets.json
100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 10.6M/10.6M [00:00<00:00, 49.6MB/s]

'tweets.json'

In [3]:
df = pd.read_json('/content/tweets.json')
df = df.transpose(copy=False)

In [4]:
df.shape

(43347, 2)

In [5]:
df['tweet_text'].isnull().sum()

0

In [6]:
df['tweet_text'] = df['tweet_text'].str.replace(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?¬´¬ª‚Äú‚Äù‚Äò‚Äô]))''', " ")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [7]:
df['tweet_text'] = df['tweet_text'].str.replace("\W+", " ")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

In [8]:
df['tweet_text']=[i.lower() for i in df['tweet_text']]

In [9]:
df

,tweet_author,tweet_text
2013-07-18 09:39:46.071961602,Hematopoiesis News,scientists conducted a phase ii study of acal...
2013-07-17 03:40:32.173842437,"Michael Wang, MD",this phase 2 acalabrutinib venetoclax av trial...
2013-07-15 15:41:16.553048065,1stOncology,nice backs astrazenecas calquence for cll
2013-07-12 19:19:42.367813635,Toby Eyre,acalabrutinib is a valuable option in pts int...
2013-07-04 12:40:34.334232586,Lymphoma Hub,nice has recommended the use of acalabrutinib ...
...,...,...
1987-06-19 12:17:53.643945985,Joy is a Lifestyle,hanging out with friends ff cll happiness
1987-06-19 12:06:26.675290112,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,hanging out with friends ff cll happiness
1987-06-17 23:05:41.186953217,IQWiG,zusatznutzen von idelalisib ist weder f√ºr cll ...
1987-06-17 15:18:00.525635584,Medibooks,hematolog√≠a ptk2 expression and immunochemoth...
1987-06-13 10:44:06.537678849,Medibooks,hematolog√≠a mutations in tlr myd88 pathway id...

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [11]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('omw-1.4')
lemmatizer = WordNetLemmatizer()

def nltk_tag_to_wordnet_tag(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:          
        return None


def lemmatize_sentence(sentence):
    nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sentence))  

    wordnet_tagged = map(lambda x: (x[0], nltk_tag_to_wordnet_tag(x[1])), nltk_tagged)
    lemmatized_sentence = []
    for word, tag in wordnet_tagged:
        if tag is None:

            lemmatized_sentence.append(word)
        else:        

            lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
    return " ".join(lemmatized_sentence)


df['tweet_text'] = df['tweet_text'].apply(lambda x: lemmatize_sentence(x))

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [12]:
df

,tweet_author,tweet_text
2013-07-18 09:39:46.071961602,Hematopoiesis News,scientist conduct a phase ii study of acalabru...
2013-07-17 03:40:32.173842437,"Michael Wang, MD",this phase 2 acalabrutinib venetoclax av trial...
2013-07-15 15:41:16.553048065,1stOncology,nice back astrazenecas calquence for cll
2013-07-12 19:19:42.367813635,Toby Eyre,acalabrutinib be a valuable option in pt intol...
2013-07-04 12:40:34.334232586,Lymphoma Hub,nice have recommend the use of acalabrutinib f...
...,...,...
1987-06-19 12:17:53.643945985,Joy is a Lifestyle,hang out with friend ff cll happiness
1987-06-19 12:06:26.675290112,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,hang out with friend ff cll happiness
1987-06-17 23:05:41.186953217,IQWiG,zusatznutzen von idelalisib ist weder f√ºr cll ...
1987-06-17 15:18:00.525635584,Medibooks,hematolog√≠a ptk2 expression and immunochemothe...
1987-06-13 10:44:06.537678849,Medibooks,hematolog√≠a mutation in tlr myd88 pathway iden...

In [13]:
df.reset_index(inplace = True)

In [14]:
df

,index,tweet_author,tweet_text
0,2013-07-18 09:39:46.071961602,Hematopoiesis News,scientist conduct a phase ii study of acalabru...
1,2013-07-17 03:40:32.173842437,"Michael Wang, MD",this phase 2 acalabrutinib venetoclax av trial...
2,2013-07-15 15:41:16.553048065,1stOncology,nice back astrazenecas calquence for cll
3,2013-07-12 19:19:42.367813635,Toby Eyre,acalabrutinib be a valuable option in pt intol...
4,2013-07-04 12:40:34.334232586,Lymphoma Hub,nice have recommend the use of acalabrutinib f...
...,...,...,...
43342,1987-06-19 12:17:53.643945985,Joy is a Lifestyle,hang out with friend ff cll happiness
43343,1987-06-19 12:06:26.675290112,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,hang out with friend ff cll happiness
43344,1987-06-17 23:05:41.186953217,IQWiG,zusatznutzen von idelalisib ist weder f√ºr cll ...
43345,1987-06-17 15:18:00.525635584,Medibooks,hematolog√≠a ptk2 expression and immunochemothe...
43346,1987-06-13 10:44:06.537678849,Medibooks,hematolog√≠a mutation in tlr myd88 pathway iden...

Sentiment

In [15]:
df['overall_polarity']=0

In [16]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
     |‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 125 kB 7.6 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from vaderSentiment) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (1.24.3)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [17]:
obj = SentimentIntensityAnalyzer()

In [18]:
for i in range(len(df['tweet_text'])):
  di = obj.polarity_scores(df.iloc[i,1])
  c = list(di.values())
  c = c.index(max(c))
  if c == 0:
    df['overall_polarity'][i]='Negative'
  elif c== 1:
    df['overall_polarity'][i]='Neutral'
  elif c == 2:
    df['overall_polarity'][i]='Positive'
  else:
    df['overall_polarity'][i]='compound'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [19]:
df

,index,tweet_author,tweet_text,overall_polarity
0,2013-07-18 09:39:46.071961602,Hematopoiesis News,scientist conduct a phase ii study of acalabru...,Neutral
1,2013-07-17 03:40:32.173842437,"Michael Wang, MD",this phase 2 acalabrutinib venetoclax av trial...,Neutral
2,2013-07-15 15:41:16.553048065,1stOncology,nice back astrazenecas calquence for cll,Neutral
3,2013-07-12 19:19:42.367813635,Toby Eyre,acalabrutinib be a valuable option in pt intol...,Neutral
4,2013-07-04 12:40:34.334232586,Lymphoma Hub,nice have recommend the use of acalabrutinib f...,Neutral
...,...,...,...,...
43342,1987-06-19 12:17:53.643945985,Joy is a Lifestyle,hang out with friend ff cll happiness,compound
43343,1987-06-19 12:06:26.675290112,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,hang out with friend ff cll happiness,Neutral
43344,1987-06-17 23:05:41.186953217,IQWiG,zusatznutzen von idelalisib ist weder f√ºr cll ...,Neutral
43345,1987-06-17 15:18:00.525635584,Medibooks,hematolog√≠a ptk2 expression and immunochemothe...,Neutral
43346,1987-06-13 10:44:06.537678849,Medibooks,hematolog√≠a mutation in tlr myd88 pathway iden...,Neutral

In [20]:
import spacy
from spacy import displacy

NER = spacy.load("en_core_web_sm")

In [21]:
dit = []

In [22]:
for i in range(len(df['tweet_text'])):
  raw_text=df['tweet_text'][i]
  text1 = NER(raw_text)
  for word in text1.ents:
    t = []
    t.append(word.text)
    t.append(df.iloc[i,1])
    t.append(df.iloc[i,3])
    dit.append(t)

In [23]:
newdf = pd.DataFrame(dit,columns=['entity','author_name','overall_polarity'])

In [24]:
newdf.drop_duplicates(inplace = True)
newdf.reset_index(inplace = True, drop = True)
newdf

,entity,author_name,overall_polarity
0,73,Hematopoiesis News,Neutral
1,2,"Michael Wang, MD",Neutral
2,pharma healthnews,European Pharmaceutical Review,Neutral
3,tobyeyre82,Graham Collins,Neutral
4,cll,CLL Ireland,Neutral
...,...,...,...
33748,600,Miche√°l üáÆüá™,Neutral
33749,liverpool,Miche√°l üáÆüá™,Neutral
33750,cll,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,Neutral
33751,zusatznutzen von idelalisib,IQWiG,Neutral
33752,hematolog√≠a ptk2 expression,Medibooks,Neutral

In [25]:
newdf['frequency'] = newdf.groupby('entity')['entity'].transform('count')

In [26]:
newdf

,entity,author_name,overall_polarity,frequency
0,73,Hematopoiesis News,Neutral,8
1,2,"Michael Wang, MD",Neutral,415
2,pharma healthnews,European Pharmaceutical Review,Neutral,1
3,tobyeyre82,Graham Collins,Neutral,7
4,cll,CLL Ireland,Neutral,1030
...,...,...,...,...
33748,600,Miche√°l üáÆüá™,Neutral,18
33749,liverpool,Miche√°l üáÆüá™,Neutral,8
33750,cll,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,Neutral,1030
33751,zusatznutzen von idelalisib,IQWiG,Neutral,1
33752,hematolog√≠a ptk2 expression,Medibooks,Neutral,1

In [27]:
newdf[['entity','frequency']].to_csv('objective1.csv')

In [28]:
newdf[['entity', 'author_name', 'overall_polarity']].to_csv('objective2.csv')

In [31]:
sol1 = newdf[['entity','frequency']]
sol1

                            entity  frequency
0                               73          8
1                                2        415
2                pharma healthnews          1
3                       tobyeyre82          7
4                              cll       1030
...                            ...        ...
33748                          600         18
33749                    liverpool          8
33750                          cll       1030
33751  zusatznutzen von idelalisib          1
33752  hematolog√≠a ptk2 expression          1

[33753 rows x 2 columns]

In [32]:
sol2 = newdf[['entity', 'author_name', 'overall_polarity']]
sol2

,entity,author_name,overall_polarity
0,73,Hematopoiesis News,Neutral
1,2,"Michael Wang, MD",Neutral
2,pharma healthnews,European Pharmaceutical Review,Neutral
3,tobyeyre82,Graham Collins,Neutral
4,cll,CLL Ireland,Neutral
...,...,...,...
33748,600,Miche√°l üáÆüá™,Neutral
33749,liverpool,Miche√°l üáÆüá™,Neutral
33750,cll,ùìíùìªùì≤ùîÉùîÉùîÇ ùìüùìÆùìªùìªùîÇüåπ,Neutral
33751,zusatznutzen von idelalisib,IQWiG,Neutral
33752,hematolog√≠a ptk2 expression,Medibooks,Neutral